// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcLsZtE58mrFGBy82XSFNyPDr86EE2FE8',
    appId: '1:382121001917:web:3197e408a93298534948d4',
    messagingSenderId: '382121001917',
    projectId: 'esports-98e21',
    authDomain: 'esports-98e21.firebaseapp.com',
    storageBucket: 'esports-98e21.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQl-_b9wTpn1PO7M5SG78HllUB7Y6DJWo',
    appId: '1:382121001917:android:055d98524055ecf74948d4',
    messagingSenderId: '382121001917',
    projectId: 'esports-98e21',
    storageBucket: 'esports-98e21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3SydIe-_hCO18HNUib0BoKP3EjZCFEIg',
    appId: '1:382121001917:ios:223021328f9f44004948d4',
    messagingSenderId: '382121001917',
    projectId: 'esports-98e21',
    storageBucket: 'esports-98e21.appspot.com',
    iosClientId: '382121001917-ibhfmd2f8j98d29s1rgn6q50ii9odgqu.apps.googleusercontent.com',
    iosBundleId: 'com.example.web',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3SydIe-_hCO18HNUib0BoKP3EjZCFEIg',
    appId: '1:382121001917:ios:223021328f9f44004948d4',
    messagingSenderId: '382121001917',
    projectId: 'esports-98e21',
    storageBucket: 'esports-98e21.appspot.com',
    iosClientId: '382121001917-ibhfmd2f8j98d29s1rgn6q50ii9odgqu.apps.googleusercontent.com',
    iosBundleId: 'com.example.web',
  );
}
